name: flutter_instagram
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.4.5
  uuid: ^4.2.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  firebase_storage: ^11.4.1
  cloud_firestore: ^4.12.2
  font_awesome_flutter: ^10.6.0
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  image: ^4.1.3
  collection: ^1.17.1
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.7.2
  lottie: ^2.6.0
  share_plus: ^7.2.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json

